require 'test_helper'

class Articles::PostTest < ActiveSupport::TestCase
  def setup
    @post = Factory 'Articles::Post'
  end
  
  test "Test factories" do
    assert @post.present?
  end

  test "Name must be present" do
    post = Articles::Post.new :content => 'test'
    assert !post.valid?
  end
  
  test "Name must be unique" do
    post = Articles::Post.new :name => 'First post', :content => 'This is my super post'
    
    assert !post.save, "Should fail as this post exist in factories."
  end

  test "Url name must be autogenerated and unique" do
    assert @post.url_name.present?, "url_name must be present after saving a valid page."
  end
  
  test "Page should accept keywords" do
    @post.keyword_list = 'this, are, my, keywords'
    assert @post.valid?
    assert @post.save!
  end
end
