require 'test_helper'

class ArticleTest < ActiveSupport::TestCase
  def setup
    @article = Factory :article
  end
  
  test "Test factories" do
    assert @article.present?
  end

  test "Name must be present" do
    article = Article.new :content => 'test'
    assert !article.valid?
  end
  
  test "Name must be unique" do
    article = Article.new :name => 'First article', :content => 'This is my super article'
    assert !article.save, "Should fail as this article exist in factories."
  end

  test "Url name must be autogenerated and unique" do
    assert @article.url_name.present?, "url_name must be present after saving a valid page."
  end
  
  test "Page should accept keywords" do
    @article.keyword_list = 'this, are, my, keywords'
    assert @article.valid?
    assert @article.save!
  end
end
