require 'test_helper'

class PageTest < ActiveSupport::TestCase
  # Replace this with your real tests.
  test "Name must be present" do
    @page = Page.new
    assert !@page.save, "Should fail as name is not present."
  end
  
  test "Name must be unique" do
    @page = Page.new :name => 'Conoce', :content => 'my very long content that should pass as it is longer than 50 characters.', :section_id => 1
    
    assert !@page.save, "Should fails as this page exist in the pages fixtues."
  end
  
  test "Url name must be autogenerated and unique" do
    @page = Page.new :name => 'Contacto', :content => 'Please drop us a line through our friendly contact form.', :section_id => 1
    @page.save
    
    assert @page.url_name.present?, "url_name must be present after saving a valid page."
  end
  
  test "Content must be present be at least 50 characters long" do
    @page = Page.new :name => 'Web', :section_id => 1
    
    assert !@page.valid?, "This should not pass as content is not present."
    @page.content = 'test'
    assert !@page.valid?, "This should not pass as content is not at least 50 characters long." 
    @page.content = 'This is my new content that should make my test pass with its new length.'
    
    assert @page.valid?, "This should now pass"
  end
  
  test "Page should belong to a section" do
    @page = Page.new :name => 'Web', :content => 'This is my new content that should make my test pass with its new length.'
    assert !@page.valid?, 'This should not pass as this page is not related to any section.'
  end
end
