require 'test_helper'

class PageTest < ActiveSupport::TestCase
  def setup
    @section  = Factory.create(:section)
    @page     = Factory.create(:page, :section_id => @section.id)
  end

  test "Name must be present" do
    page = Page.new
    assert page.invalid?, "Should fail as name is not present."
  end

  test "Name must be unique" do
    page = Factory.build(:page)
    assert page.invalid?, "Should fails as this page exist in factories."
  end

  test "Url name must be autogenerated and unique" do
    page = Factory.create(:page, :name => "Contacto", :section => @section)
    assert page.url_name.present?, "url_name must be present after saving a valid page."
  end

  test "Page should belong to a section" do
    page = Page.new :name => 'Web', :content => 'This is my new content that should make my test pass with its new length.'
    assert page.invalid?, 'This should not pass as this page is not related to any section.'
  end

  test "Page should accept keywords" do
    @page.keyword_list = 'this, are, my, keywords'
    assert @page.valid?
    assert @page.save!
  end
end
