require 'test_helper'
require File.join(File.dirname(__FILE__), '..', 'factories')

class PageTest < ActiveSupport::TestCase
  def setup
    @section  = Factory(:section)
    @page     = Factory(:page, :section_id => @section.id)
  end
  
  test "Name must be present" do
    @page = Page.new
    assert !@page.save, "Should fail as name is not present."
  end
  
  test "Name must be unique" do
    @page = Page.new :name => 'My new page', :content => 'This is my super page', :section_id => 1
    
    assert !@page.save, "Should fails as this page exist in factories."
  end
  
  test "Url name must be autogenerated and unique" do
    @page = Page.new :name => 'Contacto', :content => 'Please drop us a line through our friendly contact form.', :section_id => 1
    @page.save
    
    assert @page.url_name.present?, "url_name must be present after saving a valid page."
  end
  
  test "Page should belong to a section" do
    @page = Page.new :name => 'Web', :content => 'This is my new content that should make my test pass with its new length.'
    assert !@page.valid?, 'This should not pass as this page is not related to any section.'
  end
end
