require 'test_helper'

class SectionTest < ActiveSupport::TestCase
  
  test "Name must be present" do
    @section = Section.new
    
    assert !@section.save, "It should not pass as no title has been defined"
  end
  
  test "Name must be unique" do
    @section = Section.new :name => 'Main' 
    
    assert !@section.valid?, "Section invalid as title is already in use."
    
    @section.name = 'Contact'
    
    assert @section.valid?, "Section should pass now."
  end
  
  test "url_name should be auto generated and unique" do
    @section = Section.create :name => 'New Title'
    
    assert @section.url_name.present?, "Name should be auto generated by the model."
  end
  
  test "Name should be unique, therefore title must be unique" do
    @section = Section.new :name => 'Main '
    # Even though 'Main ' and 'Main' are different strings, the section should not be valid
    @section.save
    
    assert !@section.valid?, "Name should not be repeated"
  end
end
